### PR TITLE
drop only the netsize.adj offset in predict.ergm.ego

### PR DESCRIPTION
**Pull request by chad-klumb**
references statnet/ergm#172

### CODE REVIEW

**Comment by martinamorris** [comment]
Thanks @chad-klumb -- any idea why the appveyor build is failing -- it seems to be having problems installing dependencies from github.

**Comment by chad-klumb** [comment]
It's looking for a C compiler where one doesn't exist

```
/bin/sh: c:/rtools40/mingw64/bin/gcc: No such file or directory
```


From the commit log

https://github.com/statnet/ergm.ego/commits/master

it appears this build hasn't been working for some time.

**Comment by martinamorris** [comment]
so both travis and appveyor are failing.  same reason?  is this something we can fix?

**Review by mbojan — APPROVED** [review]
Looks OK to me. Thanks @chad-klumb !

**Comment by mbojan** [comment]
Merging as the failures seem to be related to CI infrastructure only.

**Pull request merged**
