### PR TITLE
ego terms update

### PR DESCRIPTION
**Pull request by chad-klumb**
fixes statnet/ergm.ego#26

fixes statnet/ergm.ego#27

notes:

there is no term versioning in ergm.ego

mean.age is not tested as I don't see an ergm analogue

### CODE REVIEW

**Comment by krivit** [comment]
`mean.age` is in `tergm`. Don't worry about it.

**Comment by krivit** [comment]
@chad-klumb , Travis CI seems to be malfunctioning. Can you please confirm that you've run R CMD check on your branch and that nothing is broken? Thanks in advance.

**Comment by chad-klumb** [comment]
I did run R CMD check and everything was fine.

I just noticed we still need deprecation messages, though.  Also, I thought of a better implementation for nodemix's new levels argument.

I can get both of those in tomorrow.

Is there a preferred message writer at this point?

**Comment by krivit** [comment]
Thanks! Message writer?

**Comment by chad-klumb** [comment]
I meant the function called to write the messages

I used `message` in the current PR but that could easily be changed to something else

**Comment by krivit** [comment]
No, message is probably the best. We should probably implement the same template mechanism as we have for `InitErgmTerm`, but that's in the future.

**Pull request merged**
